### ISSUE TITLE
Customizable Naming Convention Code Smell

### ISSUE THREAD

**Issue by BermudaLamb** [SonarSource/sonar-dotnet#2654] opened 2019-09-16 21:00 UTC
### Description

Method parameters should follow a naming convention

### Expected behavior

As an organization I should be able to override this to be compliant with internal coding standards.

### Actual behavior

Rule is enforced with no way to customize / override it for organizational standards.

### Related information

* Visual Studio Version: 2017
* If running through the Scanner for MSBuild, its version: 4.7.1

**Comment by andrei-epure-sonarsource** [comment] 2019-10-09 14:07
thanks @BermudaLamb 
I'm closing it as duplicate of #320

**Closed by andrei-epure-sonarsource** 2019-10-09 14:07 UTC
Labels: Area: C#, Area: Rules, Status: Duplicate, Type: Improvement
