### ISSUE TITLE
 .NET 10 ccov report seems not to show up in SC

### ISSUE THREAD

**Issue by mary-georgiou-sonarsource** [SonarSource/sonar-dotnet#5820] opened 2022-07-08 14:06 UTC
In #5808 SonarCloud, without any particular change in the code, started reporting one of the conditions in [this](https://sonarcloud.io/code?id=sonaranalyzer-dotnet&pullRequest=5808&selected=sonaranalyzer-dotnet%3Aanalyzers%2Fsrc%2FSonarAnalyzer.Common%2FRules%2FVariableUnusedBase.cs&line=46) line as uncovered while locally the Unit Tests do cover this line.

The `c.SemanticModel.GetDeclaredSymbol(variable)` is only null for the C# 10 tests that contain tuples (the reported as uncovered condition runs only for the C# 10 tests).

**Comment by andrei-epure-sonarsource** [comment] 2023-03-22 08:39
@costin-zaharia-sonarsource I see you removed the Bug label - why is it a tooling issue?

Is it a user facing functionality?

**Comment by costin-zaharia-sonarsource** [comment] 2023-03-22 10:22
The way I understand this card is that for our code, the coverage is not properly displayed in SonarCloud. This could be a tooling issue and not a bug on our code.

To be fair the description is not clear and I'm not sure if I understand the issue correctly.

**Comment by andrei-epure-sonarsource** [comment] 2023-03-22 10:45
@mary-georgiou-sonarsource could you please add more details on this?

**Comment by mary-georgiou-sonarsource** [comment] 2023-03-24 08:07
@andrei-epure-sonarsource My bad - the links are not valid anymore so I'm not sure of the value of this issue without them.
I vaguely remember the problem but without the links, it will be just me making speculations at this point.

I think it's better to close this issue and next time I'll make sure to add a link to git master and take screenshots.

WDYT?

**Comment by andrei-epure-sonarsource** [comment] 2023-03-24 09:41
the link was leading to [VariableUnusedBase.cs](https://sonarcloud.io/code?id=sonaranalyzer-dotnet&selected=sonaranalyzer-dotnet%3Aanalyzers%2Fsrc%2FSonarAnalyzer.Common%2FRules%2FVariableUnusedBase.cs) on a PR (this is why it expired).

Back then, it was looking at line 46. From the PR you linked:
![image](https://user-images.githubusercontent.com/38876598/227480229-85f80444-8fff-467b-8b02-990d0edfa593.png)

Now, the same line is covered:
![image](https://user-images.githubusercontent.com/38876598/227480527-1ae53ede-f2de-46c1-ae63-a755ae67b8c9.png)

This might have been due since we changed to AltCover (https://github.com/SonarSource/sonar-dotnet/pull/6171), to ccov increased from 93.x% to 95.x% across our whole codebase.

So I agree we should close this ticket because this was a tooling problem which disappeared when we changed the tool.

**Closed by andrei-epure-sonarsource** 2023-03-24 09:41 UTC
Labels: Type: Tooling
