### ISSUE TITLE
S1128 False Positive

### ISSUE THREAD

**Issue by nnpcYvIVl** [SonarSource/sonar-dotnet#2751] opened 2019-10-25 13:45 UTC
The following code throws `warning S1128: Remove this unnecessary 'using'.` Isn't this a false positive? System.ComponentModel is referenced by the Win32Exception. I'm using SonarAnalyzer.CSharp version 8.0.0.9566.

```
using System.ComponentModel;

namespace S1128_False_Positive
{
    public class Class
    {
        /// <exception cref="Win32Exception">
        /// </exception>
        public void Test() => System.Console.WriteLine("Test");
    }
}
```

**Comment by andrei-epure-sonarsource** [comment] 2019-10-28 13:15
yes, this is a duplicate of #2694

**Closed by andrei-epure-sonarsource** 2019-10-28 13:15 UTC
