### ISSUE TITLE
Update S1226: Change contract of the rule to make it become more relevant

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonar-dotnet#630] opened 2017-08-01 11:48 UTC
This rule currently triggers an issue as soon as a method parameter is reassigned. With updated [RSPEC-1226](https://jira.sonarsource.com/browse/RSPEC-1226) this rule is supposed to raise an issue if an only if a method parameter, caught exception or foreach variable is reassigned without having been read before. 

To be noted that this rule must be part of Sonar way and becomes a bug detection rule.

Moreover, rule [RSPEC-3316](https://jira.sonarsource.com/browse/RSPEC-3316) should also be updated to stop spotting such kind of issues.

**Comment by rymeskar** [comment] 2019-01-24 12:18
Any news regarding this issue @fmallet and @Evangelink  ?

The initial intent of the rule is quite right and preventing one family of bugs.

However, the implementation seems to be triggering even in cases where it should not.

Example is linked list traversal:
`while (e != null)
            {
                list.Add(FormatMessage(e));
                e = e.InnerException;
            }`

**Comment by valhristov** [comment] 2019-01-28 10:13
Hi @rymeskar, I created a [new ticket](https://github.com/SonarSource/sonar-dotnet/issues/2249) from your comment. I am closing this one, as it was implemented but forgotten to be closed.

**Closed by valhristov** 2019-01-28 10:13 UTC
Labels: Area: Rules, Type: Improvement

**Comment by andrei-epure-sonarsource** [comment] 2019-04-09 15:20
Hi @rymeskar . I'm trying to reproduce the issue you reported here (for ticket #2249) and, from what I see, this has been fixed in #1712 (so included in 7.4.0.6452).

What version of the SonarAnalyzer are you using?
