### ISSUE TITLE
UtilityAnalyzer: Roll back the reversal of #6576 and bring back RegisterSemanticModelAction

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonar-dotnet#7368] opened 2023-06-12 11:42 UTC
#6576 added support for `RegisterSemanticModelAction`. The Roslyn compiler pipeline exposes several entry points into the compilation pipeline. RegisterSemanticModelAction is one of them and currently missing. #6576 was rolled back by #7262 (reasoning can be found there). The part of #6576 that added the registration including the tests should be added back to the code base. The registration of the UtilityAnalyzer should be changed to use RegisterSemanticModelAction to re-use the semantic model but only after all UtilityAnalyzer are re-worked in a way to reduce the queries to the semantic model to the absolute minimum. If this is not possible, some UtilityAnalyzer (like e.g. the symref analyzer) might opt to create there own semantic model.

**Comment by pavel-mikula-sonarsource** [comment] 2023-06-12 12:47
This has proven to cause the regression by design. Instead, the other explored improvements (reducing model quering) should be done.

We should close this as a dead end.

**Comment by martin-strecker-sonarsource** [comment] 2023-07-03 12:04
### How do we measure the regression?

- Ask Marry for the lists of projects, probably RavenDB (commit: the one on peach) and others
- Clone locally
- Current master of sonar-dotnet, Release build
  - Kill all msbuild/dotnet processes before run
  - Run the Scanner, local SQ SonarWay profile, if not reproducible use "All"
  - Produce a binlog
  - Build time is the base-line (also note the total analyzer time and the analyzer time of the TokenTypeAnalyzer)
  - Do this three times
- Create a PR with the Rollback
  - Do the same with the Release build from the PR
  - This is the second base and should be worse than the first baseline
- Fix the issues with caching one by one see #7411
- Make a new measurement after each change

### Merge acceptance criteria?

- It needs to be at least as good as the existing master

**Comment by mary-georgiou-sonarsource** [comment] 2023-07-04 08:16
The projects that had a notable regression at analysis time (see also [graphs here](https://github.com/SonarSource/sonar-dotnet/issues/6974)) and were used also later on for measurements are:

[ravendb](https://github.com/ravendb/ravendb.git): baae94d12fec8cbd7d4828f1ab3754eff2a1e74f
[akka.net](https://github.com/akkadotnet/akka.net.git):  a920b0723625e918e0b3e93e4b7f4a33e5533f5b
[fluentassertions](https://github.com/fluentassertions/fluentassertions.git): 371ab153276c19fd04c94333b3d32adb5a13b203

The two analyzers that had a notable impact were the `TokenTypeAnalyzer` and the `SymbolReferenceAnalyzer`.

**Comment by pavel-mikula-sonarsource** [comment] 2023-07-10 09:14
Once we have the need to register for semantic model, we can add the possibility to register for it any time in the future. Without using it for the utility analyzers where it didn't work.

Data has proven that possibly creating new model is much faster than trying to use the nicer registration. At the same time, Roslyn might cache those for us. Or their creation is not as expensive as the thread starvation.

**Comment by pavel-mikula-sonarsource** [comment] 2023-07-11 09:01
@martin-strecker-sonarsource I'm missing an explanation why this was reopened. The evidence proves that this approach doesn't work.

**Comment by martin-strecker-sonarsource** [comment] 2023-07-12 08:54
Both kinds of registrations do the exact same thing. I logged how the current registration uses semantic models in this branch https://github.com/SonarSource/sonar-dotnet/tree/Martin/UtilityPerf_LogSemModelCreation
The results are:
* The semanticModel of a tree is reused between the UtilityAnalyzers and the rules in 99,79% of the cases.
* In 30% of the cases the rule sees the semanticModel before any of the UtilityAnalyzers
* In 25% of the cases the rule sees the semanticModel after all of the UtilityAnalyzers

It will be interesting to see how the other registration changes the picture here. It also reuses the semanticModel but I expect some changes in the order between rules and utility analyzers.

![image](https://github.com/SonarSource/sonar-dotnet/assets/103252490/aaa6d23c-86b7-4011-b933-b8ca1c9b544f)

**Closed** 2023-11-30 09:31 UTC
Labels: Type: Performance
