### ISSUE TITLE
'Tests should include assertions' should recognize NSubstitute assertions

### ISSUE THREAD

**Issue by eugbaranov** [SonarSource/sonar-dotnet#2664] opened 2019-09-19 09:42 UTC
**Is your feature request related to a problem? Please describe.**
Quite often when testing that dependencies been used correctly the most convenient way to do it is with `NSubstitute` assertions but SonarLint doesn't consider those as such and hence tests flagged as not having assertions.

**Describe the solution you'd like**
[`NSubstitute` assertions](https://nsubstitute.github.io/help/received-calls/) should be recognized.

**Describe alternatives you've considered**
Rewriting tests to use supported assertion frameworks would make tests unnecessarily verbose.

**Comment by andrei-epure-sonarsource** [comment] 2019-09-23 13:33
thanks @eugbaranov , this is a duplicate of #1353 so will close

**Closed by andrei-epure-sonarsource** 2019-09-23 13:33 UTC
