### ISSUE TITLE
Fix S6966 FP/FN: Should not raise for EF-Core known methods

### ISSUE THREAD

**Issue by denis-troller** [SonarSource/sonar-dotnet#9306] opened 2024-05-21 09:25 UTC
### Description

S6966 identifies opportunities to use awaitable methods instead of synchronous ones.
However, [Microsoft states that AddAsync and AddRangeAsync in EF-Core should not be chosen by default in most cases](https://learn.microsoft.com/en-us/ef/core/change-tracking/miscellaneous#add-versus-addasync).

This rule should not raise when calling DBSet.Add() or DBSet.AddRange().

This has been raised over 20 times on SonarCloud last week.

**Comment by cremor** [comment] 2024-05-21 15:22
Duplicate of #9269

**Comment by martin-strecker-sonarsource** [comment] 2024-05-23 07:54
Closed as duplicate of https://github.com/SonarSource/sonar-dotnet/issues/9269

**Closed by martin-strecker-sonarsource** 2024-05-23 07:54 UTC
