### ISSUE TITLE
.editorconfig compatible rule categories

### ISSUE THREAD

**Issue by ite-klass** [SonarSource/sonar-dotnet#5399] opened 2022-02-16 11:00 UTC
The `.editorconfig` can be used to configure analyzer diagnostic severity.

```
dotnet_diagnostic.<rule ID>.severity = <severity>
dotnet_analyzer_diagnostic.category-<rule category>.severity = <severity>
```

Using the sonarlint rule IDs to adjust severity works fine. However, using a rule category to configure a whole category of rules rather than all of them individually does not.

SonarLint defines its rules with the categories `Major Code Smell`, `Minor Code Smell`, `Info Code Smell`. (As can be seen from the analyzer information and rules list in the solution explorer within VS, when inspecting the `SonarAnalyzer.CSharp.dll` resources, when using the VS configure severity quick action.)

I suspect that using spaces makes it impossible to configure them like this, or at least unclear how to configure them then?

I tried `Major Code Smell`, `MajorCodeSmell`, `Major_Code_Smell`, `Major-Code-Smell`, … but none worked.

So either I am missing something, sonarlint should define them with categories without spaces, or there is another discrepancy.

* [editorconfig anaylzer category severity](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022#set-rule-severity-of-multiple-analyzer-rules-at-once-in-an-editorconfig-file)

**Comment by csaba-sagi-sonarsource** [comment] 2022-02-16 12:39
Duplicate of https://github.com/SonarSource/sonar-dotnet/issues/4445

**Closed by csaba-sagi-sonarsource** 2022-02-16 12:39 UTC
