### ISSUE TITLE
Unused method parameters should be removed with Tuples and Dictionaries

### ISSUE THREAD

**Issue by bdovaz** [SonarSource/sonar-dotnet#4069] opened 2021-02-16 09:58 UTC
### Description

I got and "Unused method parameters should be removed" using tuples with dictionaries.

**S1172**

### Repro steps

This snippet reports:

```csharp
private bool Check(string value1, string value2) => map.ContainsKey((value1, value2));
```

Remove this parameter 'value1', whose value is ignored in the method.
Remove this parameter 'value2', whose value is ignored in the method.

**Comment by costin-zaharia-sonarsource** [comment] 2021-03-12 13:12
Hi @bdovaz, I think the root cause is the same as the one on https://github.com/SonarSource/sonar-dotnet/issues/4070 and that it was fixed by https://github.com/SonarSource/sonar-dotnet/issues/3255, delivered in [8.16 release](https://github.com/SonarSource/sonar-dotnet/releases/tag/8.16.0.25740).

The problem cannot be not reproduced anymore on the latest version.

For reference this is the snippet I've used when trying to reproduce it:
```
Dictionary<(string, string), int> map = new Dictionary<(string, string), int>();
private bool Check(string value1, string value2) => map.ContainsKey((value1, value2));
```

**Closed** 2021-03-12 13:13 UTC
