### ISSUE TITLE
Fix S2589: FP with null coalesce operator

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonar-dotnet#2407] opened 2019-04-30 10:10 UTC
### Description

sonarlint warnings ?? operator as S2589

### Repro steps

class A
{
public bool booleanVal { get; set; }
}

A aObj = null;
if(aObj?booleanVal ?? false)

You can observe the problem via the code above

### Notes
Moved from https://github.com/SonarSource/sonarlint-visualstudio/issues/880
Reported by @ilkerkaran
Possible duplicate of #2164

**Comment by andrei-epure-sonarsource** [comment] 2019-05-02 09:39
Indeed looks like duplicate of #2164, will close it. I moved the example to that ticket.

**Closed by andrei-epure-sonarsource** 2019-05-02 09:39 UTC
Labels: Area: C#, Area: Symbolic Execution, Type: Bug
