### ISSUE TITLE
No metrics on some project

### ISSUE THREAD

**Issue by W3bCorp** [SonarSource/sonar-dotnet#2595] opened 2019-08-20 12:27 UTC
### Description

On some projects, I do not have a metric on .vb while source files are well indexed.

### Repro steps

When i look the TFS activity "Run code analysis" it say : 
Sensor VB.NET Properties [vbnet]
2019-08-19T16:15:45.0075174Z 18:15:44.901 WARN: Analyzer working directory does not exist: 'G:\Builds\agents\day01\_work\1\.sonarqube\out\0\output-vbnet'. Analyzer results won't be loaded from this directory.

After search, i have found that when the line "\<Import Project="$(MSBuildToolsPath)\Microsoft.VisualBasic.targets" /\>" is not the last line of .vbproj file, no analyse is performed and no metrics are calculated (the lines of code was simply detected as "lines").

Warning : if you have Post Build Event, the tag "PropertyGroup" who contains code must be after the line "\<Import Project="$(MSBuildToolsPath)\Microsoft.VisualBasic.targets" /\>" if you you use a variable like "$(ProjectDir)" otherwhile it will be null. Visibly, no problem on analysis/metrics if this PropertyGroup is just after the mentioned line.

### Known workarounds

Simply move the lines at end of file above the tag "\</Project\>".

### Related information

* SonarQube : 7.9.1
* Sonar-scanner : 3.3.0.1492
* Visual Studio : 2017
* MsBuild : 15
* TFS : 2018

**Comment by andrei-epure-sonarsource** [comment] 2019-11-05 15:56
@duncanp-sonar  - do you reckon this is a scanner thing or is it on the plugin side?

**Comment by duncanp-sonar** [comment] 2019-11-06 11:27
@andrei-epure-sonarsource more likely to be the scanner (although I tried without success to repro the problem by moving the `Import` statement, so that might be a red herring).

The warning `Analyzer working directory does not exist` comes from the dotnet plugin, which means the S4MSB targets have been imported and executed during the build, the `end` step has generated a `sonar-project.properties` file, and the scanner-cli has been executed. The plugin is then complaining about some of the data it has been passed. So, it's more likely to be an issue with the scanner, or something specific to the particular project file/build process.

**Comment by andrei-epure-sonarsource** [comment] 2020-02-18 17:46
hi @W3bCorp - do you have a small reproducer project for this problem?

**Comment by costin-zaharia-sonarsource** [comment] 2020-10-09 14:29
I'm closing this issue for now since we cannot reproduce the problem.

**Closed by costin-zaharia-sonarsource** 2020-10-09 14:29 UTC
Labels: Status: On Hold
