### ISSUE TITLE
Fix S2583 FP: Tuple unpacking

### ISSUE THREAD

**Issue by zsolt-kolbay-sonarsource** [SonarSource/sonar-dotnet#8027] opened 2023-09-18 13:38 UTC
### Description

S2583 raises a warning for the following code:

```cs
public void Test()
{
    var x = 0;
    (x, var y) = (Random.Shared.Next(), Random.Shared.Next());

    if (x == 0)  // Noncompliant - FP
    {
        Console.WriteLine("hello world");
    }
}
```

**Note:** if the x variable is also declared inside the tuple rather than in the previous line then the warning disappears:
```cs
(var x, var y) = (Random.Shared.Next(), Random.Shared.Next());
```
### Expected behavior

The analyzer should not raise an issue.

### Actual behavior

The analyzer raises an issue: `S2583: Change this condition so that it does not always evaluate to 'True'.`

### Related information

* C#/VB.NET Plugins version: 9.10.0.77988
* Visual Studio version: Visual Studio 2022 (version 17.7)
* MSBuild / dotnet version: .NET 7.0
* Operating System: Windows 10

**Comment by mary-georgiou-sonarsource** [comment] 2023-09-27 11:46
Duplicate of https://github.com/SonarSource/sonar-dotnet/issues/7057

**Closed** 2023-09-27 11:52 UTC
Labels: Area: C#, Type: CFG/SE FPs
