### ISSUE TITLE
False positive for pattern matching

### ISSUE THREAD

**Issue by GeertvanHorrik** [SonarSource/sonar-dotnet#3781] opened 2020-11-23 09:31 UTC
### Description

Pattern matching on booleans cause false positives.

### Repro steps

![image](https://user-images.githubusercontent.com/1246444/99946607-ed909b00-2d76-11eb-9f32-272d5d1ebef2.png)

### Expected behavior

This is valid code, the if statement only checks whether an object is of a specific type, not the actual value.

### Actual behavior

The object check (pattern matching) is evaluated as a value check.

### Known workarounds

Refactoring the code is a workaround

### Related information

* SonarC#/SonarVB Version
* Scanner for MSBuild Version 5.0.3
* SonarQube version (not needed if analyzing against SonarCloud) (analyzing against SonarCloud)
* Usage: Cake

**Comment by duncanp-sonar** [comment] 2020-11-23 09:56
@GeertvanHorrik thanks for reporting the issue. Could you let us know which version of the **sonar-dotnet** plugin you are using please? (the issue is with the plugin, not the Scanner for MSBuild).

**Comment by GeertvanHorrik** [comment] 2020-11-23 10:04
@duncanp-sonar thanks for the fast response. I am using SonarCloud, do I have control over which version I am using?

**Comment by duncanp-sonar** [comment] 2020-11-23 10:29
@GeertvanHorrik no, you don't. Apologies, I missed that it was SonarCloud.

**Comment by pavel-mikula-sonarsource** [comment] 2020-11-23 11:04
Hi @GeertvanHorrik,

Thank you for reporting this case. I can confirm it as False Positive. We have the root cause with `is` pattern matching already reported in #3110 so I'll close this one.

**Closed by pavel-mikula-sonarsource** 2020-11-23 11:04 UTC
