### ISSUE TITLE
S3453 false positive for singleton of ConfigurationSection

### ISSUE THREAD

**Issue by sm-g** [SonarSource/sonar-dotnet#2677] opened 2019-09-29 17:16 UTC
### Repro steps

```
internal class MySettingsSection : ConfigurationSection
{
	private MySettingsSection()
	{
	}

	public static MySettingsSection Instance { get; } = (MySettingsSection)ConfigurationManager.GetSection("section");
}
```

### Known workarounds

Add `public static MySettingsSection Instance2 { get; } = new MySettingsSection();`

### Related information

* SonarC# Version 7.16.0.8981
* Visual Studio Version 16.3.1

**Comment by pavel-mikula-sonarsource** [comment] 2019-12-04 13:46
Hello @sm-g,

thank you for contacting us, but unfortunately we weren't able to reproduce the issue. Adding Instance property stops the S3453 from appearing.

I've also updated your sample from `(T)` to `(MySettingsSection)` since `T` was not declared. Please take a look at it or try to add more information.

**Comment by andrei-epure-sonarsource** [comment] 2020-11-02 09:27
closing it because we didn't get any response from the user

**Closed by andrei-epure-sonarsource** 2020-11-02 09:27 UTC
Labels: Status: On Hold
