### ISSUE TITLE
Rule S2479 - Verbatim interpolated string being flagged erroneously

### ISSUE THREAD

**Issue by danbrad** [SonarSource/sonar-dotnet#2839] opened 2019-11-26 15:23 UTC
### Description

When rule S2479 was implemented in #2696, verbatim strings were added as a special case with exclusions but not interpolated verbatim strings. This causes interpolated verbatim strings to be flagged erroneously.

### Repro steps

Add this code to a .cs file.

            // interpolated verbatim string
            var s = $@"
                line1
                line2
            ";

### Expected behavior

The rule should not be triggered.

### Actual behavior

The above will trigger the rule erroneously.

### Known workarounds

None

### Related information

* sonar-scanner-msbuild-4.7.1.2311-net46
* SonarLint 4.14.0.12332
* Visual Studio Version 2019

**Comment by andrei-epure-sonarsource** [comment] 2019-11-27 10:51
thanks! closing as duplicate of #2773

**Closed by andrei-epure-sonarsource** 2019-11-27 10:51 UTC

**Comment by danbrad** [comment] 2019-11-27 11:36
Oops, didn't see that issue, sorry!
