### ISSUE TITLE
S1854:Dead stores should be removed doesn't recognize parameter passed to method in exception block

### ISSUE THREAD

**Issue by absolutebandit** [SonarSource/sonar-dotnet#3327] opened 2020-05-07 10:32 UTC
### Description

A bool parameter is assigned and then passed to a method within the catch exception block but the analyzers don't recognize this so the warning/error is still displayed.

### Repro steps

```C#
        public async Task<ServicePrincipal> EnsureServicePrincipalAsync(string servicePrincipalName)
        {
            var applicationCreated = false;
            var servicePrincipalCreated = false;
            Application application = null;
            ServicePrincipal servicePrincipal = null;

            try
            {
                _logger.LogInformation("Ensure service principal {servicePrincipalName} running", servicePrincipalName);

                application = await _graphApiClient.GetApplicationByNameAsync(servicePrincipalName).ConfigureAwait(false);

                if (application == null)
                {
                    _logger.LogInformation("Creating aad application {applicationName}", servicePrincipalName);
                    application = await _graphApiClient.CreateApplicationAsync(servicePrincipalName).ConfigureAwait(false);
                    applicationCreated = true;
                }
                else
                {
                    _logger.LogInformation("Aad application {applicationName} already exists", servicePrincipalName);
                }

                servicePrincipal = await _graphApiClient.GetServicePrincipalByNameAsync(servicePrincipalName).ConfigureAwait(false);

                if (servicePrincipal == null)
                {
                    _logger.LogInformation("Creating aad service principal {servicePrincipalName}", servicePrincipalName);
                    servicePrincipal = await _graphApiClient.CreateServicePrincipalAsync(servicePrincipalName, application.AppId).ConfigureAwait(false);
                    servicePrincipalCreated = true;
                }
                else
                {
                    _logger.LogInformation("Aad service principal {servicePrincipalName} already exists", servicePrincipalName);
                }

                var clientIdName = $"{servicePrincipalName}-clientId";

                if (!await _keyVaultService.DoesKeyVaultSecretExistAsync(clientIdName).ConfigureAwait(false))
                {
                    await _keyVaultService.AddSecretToKeyVaultAsync(clientIdName, application.AppId).ConfigureAwait(false);
                }

                var clientSecretName = $"{servicePrincipalName}-clientSecret";

                if (!await _keyVaultService.DoesKeyVaultSecretExistAsync(clientSecretName).ConfigureAwait(false))
                {
                    var passwordCredential = await _graphApiClient.CreateApplicationPasswordAsync(application.Id).ConfigureAwait(false);
                    await _keyVaultService.AddSecretToKeyVaultAsync(clientSecretName, passwordCredential.SecretText).ConfigureAwait(false);
                }

                _logger.LogInformation("Ensure service principal {servicePrincipalName} completed successfully", servicePrincipalName);

                return servicePrincipal;
            }
            catch (Exception exception)
            {
                _logger.LogError(exception, "Error ensuring service principal {servicePrincipalName}", servicePrincipalName);
                await UndoServicePrincipalAsync(applicationCreated, application, servicePrincipalCreated, servicePrincipal).ConfigureAwait(false);
                throw;
            }
        }
````

### Expected behavior

No warning raised about "applicaitonCreated" and "servicePrincipalCreated" booleans.

### Actual behavior

Warning is raised about "applicaitonCreated" and "servicePrincipalCreated" booleans.

### Known workarounds

Disable the rule.

### Related information

* C#/VB.NET Plugins Version
* Visual Studio Version
* MSBuild / dotnet version
* If running through the Scanner for MSBuild, its version
* Operating System

**Comment by pavel-mikula-sonarsource** [comment] 2020-05-08 06:36
Hi @absolutebandit ,

Thank you for reporting this issue. We can confirm this as false positive. It has same root cause as #2600 so I'll close this issue and put a note there.

Here's a shorter reproducer for future reference:
```C#
public string Main(string value)
{
    bool created = false;
    try
    {
        if (value == null)
        {
            value = "";
            created = true;
        }
        return value;
    }
    catch (Exception exception)
    {
        Log(created);
        throw;
    }
}

private void Log(bool created)
{
}
```

**Closed by pavel-mikula-sonarsource** 2020-05-08 06:36 UTC
