### ISSUE TITLE
False Positive S2589: assignments in local functions

### ISSUE THREAD

**Issue by eduherminio** [SonarSource/sonar-dotnet#3701] opened 2020-11-01 19:07 UTC
### Description

S2589 doesn't take into account assignments that happen inside of local functions.

### Repro steps

[SonarCloud project](https://sonarcloud.io/project/issues?id=SheepTools&issues=AXWESiOjlR-v0Yupw4Fk&open=AXWESiOjlR-v0Yupw4Fk)

### Expected behavior

No warning triggered.

### Actual behavior

Change this condition so that it does not always evaluate to 'true'

### Related information

* SonarCloud
* .NET Core 3.1.403

**Comment by pavel-mikula-sonarsource** [comment] 2020-11-02 10:40
Hi @eduherminio,

Thank you for reporting this case. I can confirm it as a False Positive. Our Symbolic Excution engine currently doesn't support local functions.

**Comment by pavel-mikula-sonarsource** [comment] 2020-11-05 12:35
I'm closing this issue, we have similar one reported in #3161. It shares the same root cause so I'll update the title to both rules.

**Closed by pavel-mikula-sonarsource** 2020-11-05 12:35 UTC
Labels: Area: C#, Area: CFG, Type: False Positive
