### ISSUE TITLE
Sonnar Scanner for MSBuild fails to merge report results from different formats

### ISSUE THREAD

**Issue by fiuzafrancisco** [SonarSource/sonar-dotnet#5803] opened 2022-06-30 15:52 UTC
Hello, 

I have a set of XUnit tests that I can successfully see in SonarQube using the parameter "sonar.cs.xunit.reportsPaths".
I also have a set of Cypress integration tests that I can also successfully see in SonarQube using the "Generic Test Execution Report Format" with the parameter "sonar.testExecutionReportPaths".

But when I try to see both of them, only the report defined in  "sonar.testExecutionReportPaths" is visible in SonarQube, even though I can see in the output of the "SonarScanner.MSBuild.exe end" that the xunit tests reports has also been processed. 

Thank you for your support!

**Comment by andrei-epure-sonarsource** [comment] 2022-07-20 16:51
Duplicate of https://community.sonarsource.com/t/load-multiple-report-files-in-sonarqube/67126

**Closed by andrei-epure-sonarsource** 2022-07-20 16:51 UTC
