### ISSUE TITLE
Fix S3900 FP: Recognize ArgumentNullException.ThrowIfNull()

### ISSUE THREAD

**Issue by bart-vmware** [SonarSource/sonar-dotnet#5729] opened 2022-06-12 19:07 UTC
### Description
S3900 (Arguments of public methods should be validated against null) does not recognize the usage of `ArgumentNullException.ThrowIfNull()`, which was [added in .NET 6](https://docs.microsoft.com/en-us/dotnet/api/system.argumentnullexception.throwifnull?view=net-6.0).

### Repro steps
```c#
public class Example
{
    public void Run(string name)
    {
        ArgumentNullException.ThrowIfNull(name);

        int len = name.Length; // FP S3900
    }
}
```

![image](https://user-images.githubusercontent.com/104792814/173249167-1712ea8e-7301-4d62-ad59-4127d6d4627d.png)

### Expected behavior
No warning reported.

### Actual behavior
Warning reported.

### Known workarounds
Suppress S3900.

### Related information
* C#/VB.NET Plugins version: SonarAnalyzer.CSharp (NuGet package) v8.40.0.48530
* Visual Studio version: Microsoft Visual Studio Community 2022 (64-bit) v17.2.3
* MSBuild version: Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework, v17.2.1.25201
* dotnet version: v6.0.300
* SonarScanner for .NET version (if used): ?
* Operating System: Windows 10 Enterprise 21H2 x64 ENU, v19044.1706

**Comment by pavel-mikula-sonarsource** [comment] 2022-06-13 06:38
Hi @bart-vmware,

Thank you for reporting this, I confirm it as FP. We plan to fix it as part of MMF-2401 (not a public link, unfortunately)

**Comment by bart-vmware** [comment] 2022-06-14 10:34
The same issue applies to:
- S4456: Parameter validation in yielding methods should be wrapped
- S4456: Parameter validation in yielding methods should be wrapped

I couldn't find a product roadmap. Do you have any idea or rough estimation when this will be released?

**Comment by pavel-mikula-sonarsource** [comment] 2022-06-14 12:22
Please create a new issue with reproducers for the S4456. That has a different root cause (and might be way easier to fix).

There's no official ETA for the MMFs. My guess is that MMF-2401 will be available in 3rd release from now.

**Comment by bart-vmware** [comment] 2022-06-15 07:01
Thanks, that estimation is helpful. I've created #5744 for S4456/S4457.

**Comment by martin-strecker-sonarsource** [comment] 2022-09-13 11:34
see also #6083

**Comment by pavel-mikula-sonarsource** [comment] 2023-02-27 14:11
The implementation should also cover `ArgumentException.ThrowIfNullOrEmpty`

**Comment by milbrandt** [comment] 2023-03-08 18:20
It's hard to accept, that this is not fixed in the current 9.9 LTS. As the next LTS will be in around 18 month, i.e. autumn 2024, then the next .NET 8 LTS  with C# 12 will be deliverd for several months. And SonarQube we can no longer update the scanners of an installed SonarQube server.

**Comment by martin-strecker-sonarsource** [comment] 2023-04-20 15:09
`ArgumentNullException.ThrowIfNull()` is supported by S3900 in [version 8.56](https://github.com/SonarSource/sonar-dotnet/releases/tag/8.56.0.67649) of the analyzer. The issue stays open until https://github.com/SonarSource/sonar-dotnet/pull/7039 is merged which contains test coverage for the feature.

**Closed** 2023-04-25 14:20 UTC
Labels: Area: C#, Type: CFG/SE FPs, Sprint: SE

**Comment by Mrxx99** [comment] 2023-12-12 16:13
I am on Version 9.9.3 (build 79811) (selfhosted) and ArgumentNullException.ThrowIfNull is not recognized.
e.g. code like this:

```csharp
string Method(string parameter)
{
  ArgumentNullException.ThrowIfNull(parameter);
  return paramter.ToUpper();
}
Still produces S3900.
