### ISSUE TITLE
Fix S1172 FP: When method parameters is used to retrieve an action

### ISSUE THREAD

**Issue by hankovich** [SonarSource/sonar-dotnet#7717] opened 2023-08-02 16:41 UTC
### Repro steps

```csharp
static void ConfigureServices()
{
    IServiceCollection services = null!;
    IConfiguration configuration = null!;

    void ConfigureOptions<TOptions>(string sectionKey) // <- S1172 sectionKey is not used
        where TOptions : class
    {
        services.Configure<TOptions>(configuration
            .GetSection(sectionKey)
            .Bind);
    }
}
```

### Related information

* C#/VB.NET Plugins version 9.6.0.74858

**Comment by mary-georgiou-sonarsource** [comment] 2023-08-03 13:18
Hello @hankovich, 
I confirm this is an FP.
I'll add this issue to our backlog to deal with it in a future sprint.

**Comment by mary-georgiou-sonarsource** [comment] 2023-08-03 13:29
duplicate of https://github.com/SonarSource/sonar-dotnet/issues/5338

**Comment by hankovich** [comment] 2023-08-03 15:17
Are you sure it's a duplicate? As I see the issue you mentioned is about using parameter as an extension delegate target, but `sectionKey` is not target of an extension delegate

**Comment by mary-georgiou-sonarsource** [comment] 2023-08-04 09:36
Hello, @hankovich  - to me it seems to be [the same root cause](https://github.com/dotnet/roslyn/issues/56644#issuecomment-1031505579).
Once the `Bind` is added to request the delegate for it rather than invoke it, the `ParameterReferenceOperation` for `sectionKey` disappears from the control flow graph.

**Closed by mary-georgiou-sonarsource** 2023-08-04 09:36 UTC
Labels: Type: False Positive, Area: C#
