### ISSUE TITLE
S2583 False Positive 2

### ISSUE THREAD

**Issue by nnpcYvIVl** [SonarSource/sonar-dotnet#2597] opened 2019-08-22 01:59 UTC
In the following code, SonarAnalyzer.CSharp 7.16.0.8981 flags `S2583 Change this condition so that it does not always evaluate to 'false'; some subsequent code is never executed`. Is this a false positive?

```
using System.IO;

namespace S2583_False_Positive
{
    public static class C
    {
        public static void M(string path, int timeoutmilliseconds = 500)
        {
            bool deletesuccess = false;
            do
            {
                try
                {
                    File.Delete(path);
                    deletesuccess = true;
                }
                catch (IOException)
                {
                    System.Threading.Thread.Sleep(timeoutmilliseconds);
                }
            } while (!deletesuccess);
        }
    }
}

```

**Comment by andrei-epure-sonarsource** [comment] 2019-08-23 15:11
Thanks a lot @nnpcYvIVl for your continuing contributions to this project!

I confirm it's an FP - and it's a duplicate of #2592

**Closed by andrei-epure-sonarsource** 2019-08-23 15:11 UTC
