### ISSUE TITLE
Fix S4056 AD0001: .NET 9 RC1

### ISSUE THREAD

**Issue by bart-vmware** [SonarSource/sonar-dotnet#9670] opened 2024-09-24 15:21 UTC
### Description

Building our codebase against .NET 9 RC1 produces the following warning:
```
CSC : warning AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.SpecifyIFormatProviderOrCultureInfo' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```

### Repro steps

```c#
public class Graph
{
    private const long One = 1;
    private const long Two = 2;

    public override string ToString()
    {
        return string.Format("{0} {1} {2:f3} {3:f3}", One, One, Two / 0.5, One);
    }
}
```

### Known workarounds

None.

### Related information

* C#/VB.NET Plugins version: 9.32.0.97167
* Visual Studio version: 17.12.0 Preview 2.0
* MSBuild / dotnet version
    ```
    > dotnet --info
    .NET SDK:
     Version:           9.0.100-rc.1.24452.12
     Commit:            81a714c6d3
     Workload version:  9.0.100-manifests.67cd1eb6
     MSBuild version:   17.12.0-preview-24422-09+d17ec720d
    
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.22631
     OS Platform: Windows
     RID:         win-x64
     Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\
    
    .NET workloads installed:
    Configured to use loose manifests when installing new manifests.
     [maui-windows]
       Installation Source: VS 17.12.35309.182
       Manifest Version:    9.0.0-rc.1.24453.9/9.0.100-rc.1
       Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.maui\9.0.0-rc.1.24453.9\WorkloadManifest.json
       Install Type:              Msi
    
     [maccatalyst]
       Installation Source: VS 17.12.35309.182
       Manifest Version:    17.5.9270-net9-rc1/9.0.100-rc.1
       Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.maccatalyst\17.5.9270-net9-rc1\WorkloadManifest.json
       Install Type:              Msi
    
     [ios]
       Installation Source: VS 17.12.35309.182
       Manifest Version:    17.5.9270-net9-rc1/9.0.100-rc.1
       Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.ios\17.5.9270-net9-rc1\WorkloadManifest.json
       Install Type:              Msi
    
     [android]
       Installation Source: VS 17.12.35309.182
       Manifest Version:    35.0.0-rc.1.80/9.0.100-rc.1
       Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.android\35.0.0-rc.1.80\WorkloadManifest.json
       Install Type:              Msi
    
     [aspire]
       Installation Source: VS 17.12.35309.182
       Manifest Version:    8.2.0/8.0.100
       Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json
       Install Type:        FileBased
    
    Host:
      Version:      9.0.0-rc.1.24431.7
      Architecture: x64
      Commit:       static
    
    .NET SDKs installed:
      9.0.100-rc.1.24452.12 [C:\Program Files\dotnet\sdk]
    
    .NET runtimes installed:
      Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 9.0.0-rc.1.24431.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    
    Other architectures found:
      x86   [C:\Program Files (x86)\dotnet]
        registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
    
    Environment variables:
      Not set
    
    global.json file:
      Not found
    ```
* SonarScanner for .NET version (if used): N/A
* Operating System: Windows 11 Enterprise 23H2

**Comment by bart-vmware** [comment] 2024-09-24 15:44
Here's a runnable project, in case it helps.

[SonarAnalyzerCrash.zip](https://github.com/user-attachments/files/17117144/SonarAnalyzerCrash.zip)

**Comment by mary-georgiou-sonarsource** [comment] 2024-09-25 14:27
Hello, thanks for reporting this bug.
It will be fixed in the next release.

**Closed by mary-georgiou-sonarsource** 2024-09-25 14:27 UTC

**Comment by bart-vmware** [comment] 2024-09-25 15:31
Is there no public PR for the fix?

**Comment by mary-georgiou-sonarsource** [comment] 2024-09-25 15:43
@bart-vmware There will be, we're preparing .NET 9 support.

**Comment by bart-vmware** [comment] 2024-09-26 05:02
Then why was this issue closed, while the fix hasn't been implemented/merged yet? I'm concerned this may slip through.

**Comment by pavel-mikula-sonarsource** [comment] 2024-10-01 15:26
Hi Bart,

We have an internal working document that we're using to plan the entire .NET 9 support topic, and this document will make sure it will not be missed. We're closing the external issues, as they'll become redundant once we start the implementation.

**Comment by pavel-mikula-sonarsource** [comment] 2025-02-06 14:32
Hi Bart,

Yes, this should already be fixed. Probably since version 10.0. I tried to put the reproducer in the latest build and it did not throw an exception. Do you still see it?

**Comment by bart-vmware** [comment] 2025-02-07 16:12
It's fixed now, thanks.
