### ISSUE TITLE
Unused method parameters should be removed with String Interpolation and Dictionaries

### ISSUE THREAD

**Issue by bdovaz** [SonarSource/sonar-dotnet#4070] opened 2021-02-16 09:58 UTC
### Description

I got and "Unused method parameters should be removed" using string interpolation with dictionaries.

**S1172**

### Repro steps

This snippet reports:

```csharp
private void AddMessage(int id, string message)
{
    var date = DateTime.UtcNow;
    map[id].Add((date, $"[{date:yyyy-MM-dd HH:mm:ss}] - {message}"));
}
```

Remove this parameter 'message', whose value is ignored in the  method.

**Comment by costin-zaharia-sonarsource** [comment] 2021-03-12 12:53
Hi @bdovaz, what version of the analyzer do you use? 

I cannot reproduce the issue you describe with the latest version and I think this problem was resolved by https://github.com/SonarSource/sonar-dotnet/issues/3255 which was delivered in [8.16 release](https://github.com/SonarSource/sonar-dotnet/releases/tag/8.16.0.25740).

For reference this is the snippet I've used when trying to reproduce the problem:
```
Dictionary<int, List<(DateTime, string)>> map = new Dictionary<int, List<(DateTime, string)>>();
private void AddMessage(int id, string message)
{
    var date = DateTime.UtcNow;
    map[id].Add((date, $"[{date:yyyy-MM-dd HH:mm:ss}] - {message}"));
}
```

**Closed** 2021-03-12 12:54 UTC
