### ISSUE TITLE
S3626: False positive on return statement

### ISSUE THREAD

**Issue by bart-vmware** [SonarSource/sonar-dotnet#5691] opened 2022-06-02 08:04 UTC
### Description

The repro code below produces warning S3626. This is incorrect, because removing the statement results in compile error CS0165: Use of unassigned local variable 'value'.

### Repro steps
```c#
public class C
{
    public void M()
    {
        var resource = GetDisposable();
        int value;

        try
        {
            value = GetValue();
        }
        catch (Exception)
        {
            return; // FP S3626: Remove this redundant jump.
        }
        finally
        {
            resource?.Dispose();
        }

        value++;
        Console.WriteLine(value);
    }

    private IDisposable GetDisposable()
    {
        throw new NotImplementedException();
    }

    private int GetValue()
    {
        throw new NotImplementedException();
    }
}
```

### Expected behavior
S3626 is not reported in the code above.

### Actual behavior
S3626 is incorrectly reported.

### Known workarounds
Suppress S3626.

### Related information

* C#/VB.NET Plugins version: SonarAnalyzer.CSharp (NuGet package) v8.40.0.48530
* Visual Studio version: Microsoft Visual Studio Community 2022 (64-bit) v17.2.3
* MSBuild version: Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework, v17.2.1.25201
* dotnet version: v6.0.300
* SonarScanner for .NET version (if used): ?
* Operating System: Windows 10 Enterprise 21H2 x64 ENU, v19044.1706

**Comment by costin-zaharia-sonarsource** [comment] 2022-06-07 20:36
Hi @bart-vmware, thanks for reporting the issue. 

I'm closing it as a duplicate of https://github.com/SonarSource/sonar-dotnet/issues/3193

**Closed by costin-zaharia-sonarsource** 2022-06-07 20:36 UTC
